### PR TITLE
enable using personalized pull-secret

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
/cc @lance 
/cc @tommyd450

### CODE REVIEW

**Comment by tommyd450** [comment]
lgtm

**Review by sallyom — COMMENTED** [review]
I'm confused as to when the non-default pull secret will be required - I'm ok with adding this but eventually we'll want this script to evolve into a proper installer/CRD with fields for OIDC provider, BYO root certs, etc.

**Comment by Gregory-Pereira** [comment]
Just to clarify, Sally, By non-default pull-secret do you mean the TAS specific one that people can download from the console dot? If so that is used for metrics in the write home job to we can track usage and installations. +1 on all the other eventual requirements, I think that stuff is important, but I think it might be a good idea to implement those when we move to the operator.

**Comment by Gregory-Pereira** [comment]
Moving this to nightlyMetrics pr (#81) because it fits better there.

**Pull request closed without merging**
