### PR TITLE
Use standart crypto library to generate certificates

### PR DESCRIPTION
**Pull request by osmman**

### CODE REVIEW

**Review by sallyom — APPROVED** [review]
lgtm

**Comment by sallyom** [comment]
holding off on merging - I'm seeing this with install - but will run again since it might be an issue on my end:
```
$ oc logs -n fulcio-system fulcio-server-c4955b5d6-fx7cq
2023-12-04T18:46:13.326Z	FATAL	app/serve.go:253	error during PEM decoding
```
If @JasonPowr or @osmman can install & confirm this is not an issue, please comment!

**Comment by osmman** [comment]
Thank @sallyom for finding the bug. I fixed cause of the problem which was that I didn't encode the fulsio-root certificate into PEM format.

**Comment by sallyom** [comment]
I tested this, all works well now!

**Review by sallyom — APPROVED** [review]
LGTM (again)

**Pull request merged**
