### PR TITLE
Add easy install script

### PR DESCRIPTION
**Pull request by lkatalin**
Authored by: Veda Shankar <veda.shankar@redhat.com>
Signed-off-by: Lily Sturmann <lsturman@redhat.com>

### CODE REVIEW

**Comment by lkatalin** [comment]
Closing to add to quickstart instead

**Comment by lkatalin** [comment]
Actually I think we do want this in version control. I will add a link to it from the quickstart as well.

**Comment by sallyom** [comment]
we'll need to only install from the checked-out local repo for now, until we are serving the chart from somewhere stable. so in the script we need to comment out the last few lines and add a line to install from filesystem, like:
```shell
# TODO: uncomment to install from helm repository, install from the local repo checkout for now
#helm repo add trusted-artifact-signer https://repo-securesign-helm.apps.open-svc-sts.k1wl.p1.openshiftapps.com/helm-charts
#helm repo update
#OPENSHIFT_APPS_SUBDOMAIN=$common_name envsubst < examples/values-sigstore-openshift.yaml | helm install --debug trusted-artifact-signer trusted-artifact-signer/trusted-artifact-signer -n trusted-artifact-signer --create-namespace --values -
OPENSHIFT_APPS_SUBDOMAIN=$common_name envsubst < examples/values-sigstore-openshift.yaml | helm upgrade -i trusted-artifact-signer --debug charts/trusted-artifact-signer  -n trusted-artifact-signer --create-namespace --values -
```

**Review by sallyom — CHANGES_REQUESTED** [review]
just the suggestion about installing from filesystem - then, all good & let's merge it!

**Review by sallyom — APPROVED** [review]
LGTM

**Pull request merged**
