### PR TITLE
fix: add the missing metadata field to the example-user for keycloak

### PR DESCRIPTION
**Pull request by StinkyBenji**

### CODE REVIEW

**Comment by cooktheryan** [comment]
lgtm

**Comment by Gregory-Pereira** [comment]
Were in the process of creating our applications in our deployment environment for the next release (release-1.0.gamma) which all changes will go into. Can you switch the branch you are trying to merge into to be `release-1.0.gamma`. Thank you for the change!

**Comment by StinkyBenji** [comment]
Done :)

**Review by lance — APPROVED** [review]
/lgtm

**Pull request merged**
