### PR TITLE
Updating with Current Snapshots

### PR DESCRIPTION
**Pull request by tommyd450**
PLEASE READ.

I have not had the chance to test these just yet so if you have the time try an install thanks in advance.

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
I can test them this morning. I will circle back with the results.

**Comment by JasonPowr** [comment]
Soo, I was able to sign and verify with some caveats, when running the install script with fulcio.createcerts.enabled: true, I can sign but when I verify im running into this error:

```
Error: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
...
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE
 error verifying bundle: verifying bundle: rekor log public key not found for payload
main.go:69: error during command execution: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
...
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
 cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE
 error verifying bundle: verifying bundle: rekor log public key not found for payload
```
When I comment out this line in the install script: https://github.com/securesign/sigstore-ocp/blob/release-1.0.gamma/tas-easy-install.sh#L148, I can sign and verify which makes sense. Im assuming its the same for the installer.
And disabling the job works aswell

**Comment by tommyd450** [comment]
We could just add the clause to the install script of "Are you using your own certs Y/n" and have it skip over that?

Maybe I am misunderstanding?

**Comment by tommyd450** [comment]
@Gregory-Pereira Jason is adding that to another PR for now Im fairly sure, our "Defualt" state is to have the fulcio createcerts job disabled by default like it was in beta!

**Comment by tommyd450** [comment]
Ive also taken the liberty to update the images to Registry for the sake of QE's mirroring.

**Comment by Gregory-Pereira** [comment]
Appreciate it, you guys are killing it!

**Comment by lance** [comment]
This PR should be updated with the latest client-server image sha now that we have a solution for the build errors in konflux.

**Pull request merged**
