### PR TITLE
Added cosign/sigstore/rekor environment variables

### PR DESCRIPTION
**Pull request by sabre1041**
Added cosign/sigstore/rekor environment variables to simplify the use of RHTAS CLI's

Avoids the need to apply flags within each CLI tool

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
This PR should go against gamma release I think. Additionally I wanted to ask about the naming conventions for these env variables. [According to the documentation](https://docs.sigstore.dev/system_config/custom_components/), the only 3 that need to be set for cosign usage should be named: `SIGSTORE_REKOR_PUBLIC_KEY`, `SIGSTORE_ROOT_FILE` and `SIGSTORE_CT_LOG_PUBLIC_KEY_FILE`. Furthermore I am not seeing any other references to env variables for the other components, so I am wondering what the other `COSIGN_` prefixed env variables are.

**Comment by sabre1041** [comment]
@Gregory-Pereira if you initialize TUF roots, you do not need to set `SIGSTORE_REKOR_PUBLIC_KEY`, `SIGSTORE_ROOT_FILE`, or `SIGSTORE_CT_LOG_PUBLIC_KEY_FILE`.

The benefits of setting the environment variables included in this PR as it enables one to avoid having to set additional flags.

For example, one can run the following commands and it will automatically target the private deployment of RHTAS

Initialize TUF roots

```shell
cosign initialize
```

Sign a container image

```shell
cosign sign <image>
```

Verify signature

```shell
cosign verify. --certificate-identity=<identity> <image>
```

Signing commits require no additional actions after setting up a repository to support gitsign

Query Rekor

```shell
rekor-cli get --log-index=0
```

**Comment by Gregory-Pereira** [comment]
understood, thank you for clarifying. I will test it when I can but the changes make sense.
/lgtm
/approve

**Review by Gregory-Pereira — APPROVED** [review]

**Review by sallyom — COMMENTED** [review]
This looks good, but we can set the env variables in the cosign deployment template, also - these should replace what we currently are setting.

**Comment by sallyom** [comment]
I pulled this commit into #144 and merged, so closing this one!

**Pull request closed without merging**
