### PR TITLE
[SECURESIGN-168] | Adding Rekor-UI

### PR DESCRIPTION
**Pull request by tommyd450**
Adding Rekor-Ui to the helm chart, If anything is out of order do let me know. A test image is present as Im curently onboarding the repo with RHTAP.

### CODE REVIEW

**Review by lance — COMMENTED** [review]
Needs a chart version bump but otherwise lgtm

**Review by lance — APPROVED** [review]

**Comment by lance** [comment]
@tommyd450 can you bump the chart version on this? TY

**Comment by tommyd450** [comment]
Kind test keeps failing trying to debug why

**Comment by tommyd450** [comment]
Kind kept failing due to a wrong user account setup within the dockerfile for Rekor-ui.

**Pull request merged**
