### PR TITLE
Release 1.0.beta

### PR DESCRIPTION
**Pull request by bouskaJ**

### CODE REVIEW

**Comment by bouskaJ** [comment]
@sallyom @tommyd450 I am not sure about the chart version. Do I need to bump it up?

**Comment by tommyd450** [comment]
I believe the tests only run on main so maybe not? Im not sure to be honest.

**Comment by tommyd450** [comment]
lgtm @sallyom signed and verified fine and all pods are running with no issue!

**Comment by sallyom** [comment]
:tada: :partying_face: thank you!!

**Review by sallyom — APPROVED** [review]
LGTM

**Pull request merged**
