### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by bouskaJ**

### CODE REVIEW

**Comment by bouskaJ** [comment]
@lance @sallyom This PR update repositories and tags for the latest snapshot images. I am not sure into which namespace images should land on `registry.redhat.io`. I can update it if needed.

**Comment by bouskaJ** [comment]
@lance I used latest container from https://console.redhat.com/preview/application-pipeline/workspaces/rhtas/applications/rhtas-cli-1-0-beta/components/cosign for cosign (see https://github.com/securesign/sigstore-ocp/pull/76/commits/e1b2add796b9bf28ac0e33e35e3ee2a0228ed6ad) I hope it's correct.

**Comment by lance** [comment]
> @lance I used latest container from https://console.redhat.com/preview/application-pipeline/workspaces/rhtas/applications/rhtas-cli-1-0-beta/components/cosign for cosign (see [e1b2add](https://github.com/securesign/sigstore-ocp/commit/e1b2add796b9bf28ac0e33e35e3ee2a0228ed6ad)) I hope it's correct.

I think the image deployed there is a little old, but no real changes to the code itself has happened since then. Ideally @RobotSail or @Gregory-Pereira could deploy the latest to the consoleDot staging to test.

**Comment by lance** [comment]
> @lance @sallyom This PR updates repositories and tags for the latest snapshot images. I am not sure into which namespace images should land on `registry.redhat.io`. I can update it if needed. 

This is great - thank you! I believe the image names in the spreadsheet for registry.redhat.io are not correct. Can you temporarily use the image names that appear in quay.io, however, if you want to just move ahead with registry.redhat.io, the names in Comet _should_ be correct, IIUC. I will get you the correct prefixes/names as soon as possible.

**Comment by lance** [comment]
@bouskaJ for the registry.redhat.io image coordinates, everything is in registry.redhat.io/rhtas-tech-preview. The image names will all have a `-rhel9` suffix. So, for example, the `cloudsqlproxy` image will be at `registry.redhat.io/rhtas-tech-preview/cloudsqlproxy-rhel9`.

**Comment by lance** [comment]
@bouskaJ due to the fact that we were required to create source images for all containers, we had to re-run the builds. I will provide you the new snapshot information when I have it. Sorry about the double work on that.

**Comment by bouskaJ** [comment]
> @bouskaJ due to the fact that we were required to create source images for all containers, we had to re-run the builds. I will provide you the new snapshot information when I have it. Sorry about the double work on that.

@lance I updated images to https://console.redhat.com/preview/application-pipeline/workspaces/rhtas/applications/rhtas-stack-1-0-beta/snapshots/rhtas-stack-1-0-beta-4rdbh 

https://console.redhat.com/preview/application-pipeline/workspaces/rhtas/applications/rhtas-cli-1-0-beta/snapshots/rhtas-cli-1-0-beta-j694s

**Comment by lance** [comment]
@bouskaJ those images seem good. I will confirm with RHTAP folks today that these are what we are going with.

**Review by sallyom — COMMENTED** [review]
Thanks for this! We'll wait to merge this until the images are in place, or are they already? :eyes:

**Comment by bouskaJ** [comment]
> Thanks for this! We'll wait to merge this until the images are in place, or are they already? 👀

Hi @sallyom We would like to have everything in place before release so we are testing from `prepare_for_release` right now with the following image mirroring set
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: registries
spec:
  repositoryDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/cosign
      source: registry.redhat.io/rhtas-tech-preview/cosign-rhel9
    - mirrors:> Thanks for this! We'll wait to merge this until the images are in place, or are they already? 👀

Hi @sallyom We would like to have everything in place before release so we are testing from `prepare_for_release` right now with the following image mirroring set
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: registries
spec:
  repositoryDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/cosign
      source: registry.redhat.io/rhtas-tech-preview/cosign-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/fulcio
      source: registry.redhat.io/rhtas-tech-preview/fulcio-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/ct-server
      source: registry.redhat.io/rhtas-tech-preview/ct-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createctconfig
      source: registry.redhat.io/rhtas-tech-preview/createctconfig-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createtree
      source: registry.redhat.io/rhtas-tech-preview/createtree-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createcerts
      source: registry.redhat.io/rhtas-tech-preview/createcerts-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/rekor-server
      source: registry.redhat.io/rhtas-tech-preview/rekor-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/backfill-redis
      source: registry.redhat.io/rhtas-tech-preview/backfill-redis-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createdb
      source: registry.redhat.io/rhtas-tech-preview/createdb-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-netcat
      source: registry.redhat.io/rhtas-tech-preview/trillian-netcat-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logsigner
      source: registry.redhat.io/rhtas-tech-preview/trillian-logsigner-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logserver
      source: registry.redhat.io/rhtas-tech-preview/trillian-logserver-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/cloudsqlproxy
      source: registry.redhat.io/rhtas-tech-preview/cloudsqlproxy-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-database
      source: registry.redhat.io/rhtas-tech-preview/trillian-database-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/tuf-server
      source: registry.redhat.io/rhtas-tech-preview/tuf-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/client-server
      source: registry.redhat.io/rhtas-tech-preview/client-server-rhel9
```
This allow us to verify HELM charts configuration using DEV (quay.io) images. QE is ready to merge this.
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/fulcio
      source: registry.redhat.io/rhtas-tech-preview/fulcio-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/ct-server
      source: registry.redhat.io/rhtas-tech-preview/ct-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createctconfig
      source: registry.redhat.io/rhtas-tech-preview/createctconfig-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createtree
      source: registry.redhat.io/rhtas-tech-preview/createtree-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createcerts
      source: registry.redhat.io/rhtas-tech-preview/createcerts-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/rekor-server
      source: registry.redhat.io/rhtas-tech-preview/rekor-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/backfill-redis
      source: registry.redhat.io/rhtas-tech-preview/backfill-redis-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/createdb
      source: registry.redhat.io/rhtas-tech-preview/createdb-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-netcat
      source: registry.redhat.io/rhtas-tech-preview/trillian-netcat-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logsigner
      source: registry.redhat.io/rhtas-tech-preview/trillian-logsigner-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logserver
      source: registry.redhat.io/rhtas-tech-preview/trillian-logserver-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/cloudsqlproxy
      source: registry.redhat.io/rhtas-tech-preview/cloudsqlproxy-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-database
      source: registry.redhat.io/rhtas-tech-preview/trillian-database-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/tuf-server
      source: registry.redhat.io/rhtas-tech-preview/tuf-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/client-server
      source: registry.redhat.io/rhtas-tech-preview/client-server-rhel9
```
This allow us to verify HELM charts configuration using DEV (quay.io) images. We are ready for merge.

**Comment by lance** [comment]
@bouskaJ I have deleted the release-1.0.beta branch as we discussed in the engineering call. A new branch can be created with the images from the release. I have created a release-1.0.beta *[tag](https://github.com/securesign/sigstore-ocp/releases/tag/release-1.0.beta)* that is the commit on which the client-server image was created, but that should not interfere with a new branch by the same name.

**Pull request closed without merging**
